### ISSUE TITLE
Authorization denied - Big Sur

### ISSUE THREAD

**Issue by nospam2k** [DocSystem/tccutil#1]
sudo python3 tcc.py -e -id SermonViewer --micro
Error: unable to open database "/Users/david/Library/Application Support/com.apple.TCC/TCC.db": authorization denied

**Comment by DocSystem** [comment]
Do you have SIP enabled or Gatekeeper enabled, I don’t know if it can have an impact but when I developed it I had both disabled

**Comment by nospam2k** [comment]
No I don't. I thought that might be the case. No problem. I found a workaround so I'm ok. I just use Automator as a packager and run the jar file from shell script which already gets the right permissions. Thanks.
