### ISSUE TITLE
Mojave issue?

### ISSUE THREAD

**Issue by FreQRiDeR** [DocSystem/tccutil#2]
Tccutil.py failed to launch in Mojave until I added SHEBANG ‘#!/bin/bash/env python3.9’ at the top. Then it performed as expected. Likely because I was using zsh or it was defaulting to older python 2.7?

Cheers

**Comment by DocSystem** [comment]
I think it’s because it used python 2.7
You need to execute ``python3 tccutil.py``

**Comment by DocSystem** [comment]
Or adding ``#!/bin/bash/env python3.9`` also works
